name: Lighthouse CI

on: pull_request

jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache node modules
        uses: actions/cache@v3
        id: cache
        with:
          path: node_modules
          key: npm-packages-${{ hashFiles('**/package-lock.json') }}

      - name: Install the project dependencies
        if: steps.cache.outputs.cache-hit == false
        run: npm ci

      - name: Install @lhci/cli
        run: npm install -g @lhci/cli@0.13.x

      - name: Build the application
        run: npm run build

      - name: Run Lighthouse CI
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        run: lhci autorun || echo "Lighthouse CI 실행이 실패했어요 🥵"

      - name: Format lighthouse score
        id: format_lighthouse_score
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const createComments = require(process.cwd() + '/scripts/lighthouse.js');
            core.setOutput('comments', createComments());

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: ${{ steps.format_lighthouse_score.outputs.comments}}

      - run: echo '${{github.actor}}님! light house 보고가세용 🤨'
